### ISSUE TITLE
Print result of queries

### ISSUE THREAD

**Issue by XaLVaUA** [Roman1236/Shop#2]
Do after #1 

Do the following queries to "zhopa" table and print the result into console.

In brackets are the columns that have to be got. If no brackets get all columns.

1. Get all entities
2. Get all entities that have num >= 2
3. Get all entities without duplicates (txt, count)
4. Get count of entities that have same txt (txt, count)
5. Get sum of num of entities without duplicates that have same txt (txt, sum)

The screenshots of all results attach to comment for this issue.

**Comment by Roman1236** [comment]
![image](https://user-images.githubusercontent.com/35147356/124364987-db9ca200-dc4d-11eb-84a5-7f1f2e1a19e9.png)
![image](https://user-images.githubusercontent.com/35147356/124364988-e0f9ec80-dc4d-11eb-81de-746e1455ae36.png)
![image](https://user-images.githubusercontent.com/35147356/124364991-e5260a00-dc4d-11eb-9261-c59f62baaa78.png)
![image](https://user-images.githubusercontent.com/35147356/124364998-ea835480-dc4d-11eb-9223-db4920c1f1b5.png)
![image](https://user-images.githubusercontent.com/35147356/124365005-ee16db80-dc4d-11eb-844a-41e2b19ccda5.png)
